### ISSUE TITLE
Relative pass discription on importing modules

### ISSUE THREAD

**Issue by jins-tkomoda** [meganetaaan/moddable-examples#8]
"./" is unneeded?

- ble/keyboard
- ble/line-things

import LineThingsApplication from './line-things-application'
↓
import LineThingsApplication from 'line-things-application'

自分の環境が変な可能性もあるのですが、ble以下の2プロジェクトのmain.jsにおいて記載してある「同じディレクトリのjs読み込む時のimport」で"./"があると実行時にコケてしまうようです（xsのbugな気もしますが、、）

**Comment by meganetaaan** [comment]
手元の環境でも現象再現しました。
私の理解では、[Moddableのモジュールの参照解決](https://github.com/Moddable-OpenSource/moddable/blob/4a6c84a7fa4ca3b0593243d90e7a1edf9c22f362/documentation/tools/manifest.md#modules)は相対パスではなくmanifestファイルでの設定値に従うようなので、"./"が付くのはそもそも間違いですね。修正します。

**Comment by meganetaaan** [comment]
修正しました。
よくよく思い返すと、過去のModdableのバージョンでは読み込めていた気もしますが、他のサンプルとの表記統一も兼ねて"./"付けない書き方で揃えたいと思います。
ご指摘ありがとうございます！
